# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoSens
                                 A QGIS plugin
 This plugin enables you to download data for the GeoSens workshops. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-02
        copyright            : (C) 2021 by Nora Nieskens, University of Würzburg
        email                : nora.nieskens@stud-mail.uni-wuerzburg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoSens class from file GeoSens.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeoSens import GeoSens
    return GeoSens(iface)
